language: python
notifications:
  email: false
sudo: false
python:
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
before_install:
  - pip install codecov
script: nosetests --with-coverage
after_success:
  - codecov
